name: Sync Files

on:
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Sync Files from Source Repository
        run: |
          cd $GITHUB_WORKSPACE  # Change to the repository directory
          git config --global user.name "shoyabrazat"
          git config --global user.email "shoyu.shoyu21@gmail.com"
          git pull https://github.com/shoyabrazat/TriggerRepo.git main --no-edit
          git push -f
