name: Sync Changes from Source Repository

on:
  push:
    branches:
      - main  # Change this to match your target branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2

      - name: Sync Changes from Source Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull  # Make sure you have the latest changes from the target repository
          git push
